// Code generated by protoc-gen-go. DO NOT EDIT.
// source: k8s_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CronJob struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CronJob) Reset()         { *m = CronJob{} }
func (m *CronJob) String() string { return proto.CompactTextString(m) }
func (*CronJob) ProtoMessage()    {}
func (*CronJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{0}
}

func (m *CronJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CronJob.Unmarshal(m, b)
}
func (m *CronJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CronJob.Marshal(b, m, deterministic)
}
func (m *CronJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CronJob.Merge(m, src)
}
func (m *CronJob) XXX_Size() int {
	return xxx_messageInfo_CronJob.Size(m)
}
func (m *CronJob) XXX_DiscardUnknown() {
	xxx_messageInfo_CronJob.DiscardUnknown(m)
}

var xxx_messageInfo_CronJob proto.InternalMessageInfo

func (m *CronJob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetConfigMapRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigMapRequest) Reset()         { *m = GetConfigMapRequest{} }
func (m *GetConfigMapRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigMapRequest) ProtoMessage()    {}
func (*GetConfigMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{1}
}

func (m *GetConfigMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigMapRequest.Unmarshal(m, b)
}
func (m *GetConfigMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigMapRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigMapRequest.Merge(m, src)
}
func (m *GetConfigMapRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigMapRequest.Size(m)
}
func (m *GetConfigMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigMapRequest proto.InternalMessageInfo

func (m *GetConfigMapRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetConfigMapResponse struct {
	Config               string   `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigMapResponse) Reset()         { *m = GetConfigMapResponse{} }
func (m *GetConfigMapResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigMapResponse) ProtoMessage()    {}
func (*GetConfigMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{2}
}

func (m *GetConfigMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigMapResponse.Unmarshal(m, b)
}
func (m *GetConfigMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigMapResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigMapResponse.Merge(m, src)
}
func (m *GetConfigMapResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigMapResponse.Size(m)
}
func (m *GetConfigMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigMapResponse proto.InternalMessageInfo

func (m *GetConfigMapResponse) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type GetCronJobsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCronJobsRequest) Reset()         { *m = GetCronJobsRequest{} }
func (m *GetCronJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCronJobsRequest) ProtoMessage()    {}
func (*GetCronJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{3}
}

func (m *GetCronJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCronJobsRequest.Unmarshal(m, b)
}
func (m *GetCronJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCronJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetCronJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCronJobsRequest.Merge(m, src)
}
func (m *GetCronJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCronJobsRequest.Size(m)
}
func (m *GetCronJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCronJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCronJobsRequest proto.InternalMessageInfo

type GetCronJobsResponse struct {
	CronJobs             []*CronJob `protobuf:"bytes,1,rep,name=CronJobs,proto3" json:"CronJobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetCronJobsResponse) Reset()         { *m = GetCronJobsResponse{} }
func (m *GetCronJobsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCronJobsResponse) ProtoMessage()    {}
func (*GetCronJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{4}
}

func (m *GetCronJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCronJobsResponse.Unmarshal(m, b)
}
func (m *GetCronJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCronJobsResponse.Marshal(b, m, deterministic)
}
func (m *GetCronJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCronJobsResponse.Merge(m, src)
}
func (m *GetCronJobsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCronJobsResponse.Size(m)
}
func (m *GetCronJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCronJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCronJobsResponse proto.InternalMessageInfo

func (m *GetCronJobsResponse) GetCronJobs() []*CronJob {
	if m != nil {
		return m.CronJobs
	}
	return nil
}

type GetCronJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCronJobRequest) Reset()         { *m = GetCronJobRequest{} }
func (m *GetCronJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetCronJobRequest) ProtoMessage()    {}
func (*GetCronJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{5}
}

func (m *GetCronJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCronJobRequest.Unmarshal(m, b)
}
func (m *GetCronJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCronJobRequest.Marshal(b, m, deterministic)
}
func (m *GetCronJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCronJobRequest.Merge(m, src)
}
func (m *GetCronJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetCronJobRequest.Size(m)
}
func (m *GetCronJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCronJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCronJobRequest proto.InternalMessageInfo

func (m *GetCronJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCronJobResponse struct {
	CronJob              *CronJob `protobuf:"bytes,1,opt,name=CronJob,proto3" json:"CronJob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCronJobResponse) Reset()         { *m = GetCronJobResponse{} }
func (m *GetCronJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetCronJobResponse) ProtoMessage()    {}
func (*GetCronJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{6}
}

func (m *GetCronJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCronJobResponse.Unmarshal(m, b)
}
func (m *GetCronJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCronJobResponse.Marshal(b, m, deterministic)
}
func (m *GetCronJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCronJobResponse.Merge(m, src)
}
func (m *GetCronJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetCronJobResponse.Size(m)
}
func (m *GetCronJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCronJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCronJobResponse proto.InternalMessageInfo

func (m *GetCronJobResponse) GetCronJob() *CronJob {
	if m != nil {
		return m.CronJob
	}
	return nil
}

type CreateCronJobRequest struct {
	Template             string   `protobuf:"bytes,1,opt,name=Template,proto3" json:"Template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCronJobRequest) Reset()         { *m = CreateCronJobRequest{} }
func (m *CreateCronJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCronJobRequest) ProtoMessage()    {}
func (*CreateCronJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{7}
}

func (m *CreateCronJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCronJobRequest.Unmarshal(m, b)
}
func (m *CreateCronJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCronJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateCronJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCronJobRequest.Merge(m, src)
}
func (m *CreateCronJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCronJobRequest.Size(m)
}
func (m *CreateCronJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCronJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCronJobRequest proto.InternalMessageInfo

func (m *CreateCronJobRequest) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type CreateCronJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCronJobResponse) Reset()         { *m = CreateCronJobResponse{} }
func (m *CreateCronJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCronJobResponse) ProtoMessage()    {}
func (*CreateCronJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{8}
}

func (m *CreateCronJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCronJobResponse.Unmarshal(m, b)
}
func (m *CreateCronJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCronJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateCronJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCronJobResponse.Merge(m, src)
}
func (m *CreateCronJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCronJobResponse.Size(m)
}
func (m *CreateCronJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCronJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCronJobResponse proto.InternalMessageInfo

type DeleteCronJobRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCronJobRequest) Reset()         { *m = DeleteCronJobRequest{} }
func (m *DeleteCronJobRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCronJobRequest) ProtoMessage()    {}
func (*DeleteCronJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{9}
}

func (m *DeleteCronJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCronJobRequest.Unmarshal(m, b)
}
func (m *DeleteCronJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCronJobRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCronJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCronJobRequest.Merge(m, src)
}
func (m *DeleteCronJobRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCronJobRequest.Size(m)
}
func (m *DeleteCronJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCronJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCronJobRequest proto.InternalMessageInfo

func (m *DeleteCronJobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteCronJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCronJobResponse) Reset()         { *m = DeleteCronJobResponse{} }
func (m *DeleteCronJobResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCronJobResponse) ProtoMessage()    {}
func (*DeleteCronJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{10}
}

func (m *DeleteCronJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCronJobResponse.Unmarshal(m, b)
}
func (m *DeleteCronJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCronJobResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCronJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCronJobResponse.Merge(m, src)
}
func (m *DeleteCronJobResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCronJobResponse.Size(m)
}
func (m *DeleteCronJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCronJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCronJobResponse proto.InternalMessageInfo

type Job struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{11}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetJobsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsRequest) Reset()         { *m = GetJobsRequest{} }
func (m *GetJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobsRequest) ProtoMessage()    {}
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{12}
}

func (m *GetJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsRequest.Unmarshal(m, b)
}
func (m *GetJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsRequest.Merge(m, src)
}
func (m *GetJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobsRequest.Size(m)
}
func (m *GetJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsRequest proto.InternalMessageInfo

type GetJobsResponse struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=Jobs,proto3" json:"Jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobsResponse) Reset()         { *m = GetJobsResponse{} }
func (m *GetJobsResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobsResponse) ProtoMessage()    {}
func (*GetJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{13}
}

func (m *GetJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobsResponse.Unmarshal(m, b)
}
func (m *GetJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobsResponse.Marshal(b, m, deterministic)
}
func (m *GetJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobsResponse.Merge(m, src)
}
func (m *GetJobsResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobsResponse.Size(m)
}
func (m *GetJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobsResponse proto.InternalMessageInfo

func (m *GetJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type GetJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobRequest) Reset()         { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()    {}
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{14}
}

func (m *GetJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobRequest.Unmarshal(m, b)
}
func (m *GetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobRequest.Marshal(b, m, deterministic)
}
func (m *GetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobRequest.Merge(m, src)
}
func (m *GetJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobRequest.Size(m)
}
func (m *GetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobRequest proto.InternalMessageInfo

func (m *GetJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetJobResponse struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=Job,proto3" json:"Job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobResponse) Reset()         { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()    {}
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{15}
}

func (m *GetJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobResponse.Unmarshal(m, b)
}
func (m *GetJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobResponse.Marshal(b, m, deterministic)
}
func (m *GetJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobResponse.Merge(m, src)
}
func (m *GetJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobResponse.Size(m)
}
func (m *GetJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobResponse proto.InternalMessageInfo

func (m *GetJobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type CreateJobRequest struct {
	Template             string   `protobuf:"bytes,1,opt,name=Template,proto3" json:"Template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{16}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type CreateJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{17}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

type DeleteJobRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJobRequest) Reset()         { *m = DeleteJobRequest{} }
func (m *DeleteJobRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJobRequest) ProtoMessage()    {}
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{18}
}

func (m *DeleteJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJobRequest.Unmarshal(m, b)
}
func (m *DeleteJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJobRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJobRequest.Merge(m, src)
}
func (m *DeleteJobRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJobRequest.Size(m)
}
func (m *DeleteJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJobRequest proto.InternalMessageInfo

func (m *DeleteJobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteJobResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJobResponse) Reset()         { *m = DeleteJobResponse{} }
func (m *DeleteJobResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteJobResponse) ProtoMessage()    {}
func (*DeleteJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7903244fefde60d5, []int{19}
}

func (m *DeleteJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJobResponse.Unmarshal(m, b)
}
func (m *DeleteJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJobResponse.Marshal(b, m, deterministic)
}
func (m *DeleteJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJobResponse.Merge(m, src)
}
func (m *DeleteJobResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteJobResponse.Size(m)
}
func (m *DeleteJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJobResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CronJob)(nil), "pb.CronJob")
	proto.RegisterType((*GetConfigMapRequest)(nil), "pb.GetConfigMapRequest")
	proto.RegisterType((*GetConfigMapResponse)(nil), "pb.GetConfigMapResponse")
	proto.RegisterType((*GetCronJobsRequest)(nil), "pb.GetCronJobsRequest")
	proto.RegisterType((*GetCronJobsResponse)(nil), "pb.GetCronJobsResponse")
	proto.RegisterType((*GetCronJobRequest)(nil), "pb.GetCronJobRequest")
	proto.RegisterType((*GetCronJobResponse)(nil), "pb.GetCronJobResponse")
	proto.RegisterType((*CreateCronJobRequest)(nil), "pb.CreateCronJobRequest")
	proto.RegisterType((*CreateCronJobResponse)(nil), "pb.CreateCronJobResponse")
	proto.RegisterType((*DeleteCronJobRequest)(nil), "pb.DeleteCronJobRequest")
	proto.RegisterType((*DeleteCronJobResponse)(nil), "pb.DeleteCronJobResponse")
	proto.RegisterType((*Job)(nil), "pb.Job")
	proto.RegisterType((*GetJobsRequest)(nil), "pb.GetJobsRequest")
	proto.RegisterType((*GetJobsResponse)(nil), "pb.GetJobsResponse")
	proto.RegisterType((*GetJobRequest)(nil), "pb.GetJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "pb.GetJobResponse")
	proto.RegisterType((*CreateJobRequest)(nil), "pb.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "pb.CreateJobResponse")
	proto.RegisterType((*DeleteJobRequest)(nil), "pb.DeleteJobRequest")
	proto.RegisterType((*DeleteJobResponse)(nil), "pb.DeleteJobResponse")
}

func init() { proto.RegisterFile("k8s_service.proto", fileDescriptor_7903244fefde60d5) }

var fileDescriptor_7903244fefde60d5 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0xdd, 0x2f, 0x76, 0xdb, 0xb3, 0xb6, 0x6e, 0xee, 0x66, 0x3f, 0xba, 0x22, 0x96, 0x11, 0x6d,
	0x51, 0x08, 0xb8, 0xfa, 0x50, 0x14, 0x45, 0x58, 0xb1, 0xd4, 0xa2, 0x0f, 0xab, 0xef, 0x92, 0xd8,
	0x51, 0x8a, 0x6d, 0x12, 0x93, 0x28, 0xf8, 0xfb, 0xfc, 0x63, 0x92, 0xdc, 0x99, 0xc9, 0xe4, 0x43,
	0xec, 0x5b, 0x72, 0xe6, 0x9c, 0x73, 0xef, 0x9c, 0x9c, 0x5d, 0x38, 0xdf, 0x4f, 0xd2, 0xcf, 0xa9,
	0x4c, 0x7e, 0x5d, 0x7e, 0x91, 0x5e, 0x9c, 0x44, 0x59, 0x44, 0xbd, 0x38, 0x10, 0x77, 0x31, 0xda,
	0x24, 0x51, 0xf8, 0x2e, 0x0a, 0x88, 0x30, 0xf8, 0xe0, 0x5f, 0xcb, 0x65, 0xf7, 0xb0, 0x7b, 0xbc,
	0xbb, 0x2d, 0x9e, 0xc5, 0x11, 0xa6, 0xa7, 0x32, 0xdb, 0x44, 0xe1, 0xd7, 0xcb, 0x6f, 0xef, 0xfd,
	0x78, 0x2b, 0x7f, 0xfc, 0x94, 0x69, 0x46, 0x13, 0xf4, 0xcf, 0xe5, 0x6f, 0xc5, 0xcc, 0x1f, 0x85,
	0x07, 0xb7, 0x4a, 0x4c, 0xe3, 0x28, 0x4c, 0x25, 0xcd, 0x31, 0x64, 0x50, 0x91, 0xd5, 0x9b, 0x70,
	0x41, 0x39, 0x9f, 0x47, 0xa7, 0xca, 0x57, 0xbc, 0xe2, 0x71, 0x06, 0x55, 0x26, 0x47, 0xd8, 0xd1,
	0xd8, 0xb2, 0x7b, 0xd8, 0x3f, 0x1e, 0xaf, 0xc7, 0x5e, 0x1c, 0x78, 0x0a, 0xdb, 0x9a, 0x43, 0x71,
	0x1f, 0x4e, 0xa9, 0xd7, 0xcb, 0xee, 0xa3, 0x77, 0x76, 0xa1, 0xc6, 0xf7, 0xce, 0x2e, 0xc4, 0x0b,
	0x7b, 0xb4, 0x99, 0xf1, 0xc0, 0x04, 0x51, 0x50, 0x6b, 0x23, 0xf4, 0x99, 0x58, 0xc3, 0xdd, 0x24,
	0xd2, 0xcf, 0x64, 0x6d, 0xc8, 0x0a, 0x3b, 0x9f, 0xe4, 0x75, 0x7c, 0xe5, 0x67, 0x3a, 0x40, 0xf3,
	0x2e, 0x16, 0x98, 0xd5, 0x34, 0x3c, 0x53, 0x3c, 0x82, 0xfb, 0x46, 0x5e, 0xc9, 0x86, 0x59, 0xdb,
	0x97, 0x58, 0x60, 0x56, 0xe3, 0x2a, 0x93, 0x03, 0xf4, 0xd5, 0xd7, 0x0b, 0x2d, 0x4d, 0xfe, 0x2c,
	0x26, 0xd8, 0x3f, 0x95, 0x99, 0x1d, 0xb0, 0x87, 0xdb, 0x06, 0x51, 0x17, 0xbf, 0x83, 0x81, 0x15,
	0xec, 0x28, 0xbf, 0x75, 0x6e, 0x5f, 0x80, 0xe2, 0x1e, 0xf6, 0x98, 0xff, 0xaf, 0x30, 0x1f, 0xeb,
	0x11, 0xc6, 0x8f, 0xf7, 0x51, 0x21, 0x1a, 0xbb, 0x1c, 0x13, 0x1e, 0x26, 0x1c, 0xc4, 0x0d, 0x83,
	0x9b, 0xc2, 0xb1, 0xf8, 0xea, 0xbe, 0x0f, 0x31, 0xe1, 0x20, 0xfe, 0x13, 0xd8, 0x14, 0x8e, 0xc5,
	0x63, 0xf1, 0xfa, 0xcf, 0x00, 0x38, 0x3f, 0x49, 0x3f, 0xf2, 0xef, 0x80, 0x36, 0xb8, 0x65, 0xb7,
	0x96, 0x16, 0xf9, 0xba, 0x2d, 0x85, 0x5f, 0x2d, 0x9b, 0x07, 0x6a, 0x9d, 0x0e, 0xbd, 0xc6, 0xd8,
	0x2a, 0x2d, 0xcd, 0x35, 0xb5, 0xda, 0xed, 0xd5, 0xa2, 0x81, 0x1b, 0x87, 0x97, 0x40, 0x79, 0x40,
	0xb3, 0x2a, 0x51, 0xeb, 0xe7, 0x75, 0xd8, 0xc8, 0xdf, 0x62, 0xaf, 0xd2, 0x2f, 0x5a, 0x72, 0x75,
	0x9b, 0x35, 0x5d, 0x1d, 0xb4, 0x9c, 0xd8, 0x3e, 0x95, 0x8a, 0xb1, 0x4f, 0x5b, 0x43, 0xd9, 0xa7,
	0xbd, 0x8f, 0x1d, 0x7a, 0x86, 0x91, 0x2a, 0x19, 0x91, 0x5a, 0xda, 0x0e, 0x62, 0x5a, 0xc1, 0x8c,
	0xea, 0x09, 0x86, 0x0c, 0x92, 0x53, 0x12, 0xb4, 0x86, 0x6c, 0xc8, 0x48, 0x9e, 0x63, 0xd7, 0xf4,
	0x83, 0xdc, 0xf2, 0x6a, 0x96, 0x70, 0x56, 0x43, 0x6d, 0xad, 0xa9, 0x07, 0x6b, 0xeb, 0xad, 0x62,
	0x6d, 0xa3, 0x43, 0xa2, 0x13, 0x0c, 0x8b, 0xff, 0xcf, 0xa7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0x0d, 0xdb, 0xbe, 0x54, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// K8SServiceClient is the client API for K8SService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type K8SServiceClient interface {
	GetConfigMap(ctx context.Context, in *GetConfigMapRequest, opts ...grpc.CallOption) (*GetConfigMapResponse, error)
	GetCronJobs(ctx context.Context, in *GetCronJobsRequest, opts ...grpc.CallOption) (*GetCronJobsResponse, error)
	GetCronJob(ctx context.Context, in *GetCronJobRequest, opts ...grpc.CallOption) (*GetCronJobResponse, error)
	CreateCronJob(ctx context.Context, in *CreateCronJobRequest, opts ...grpc.CallOption) (*CreateCronJobResponse, error)
	DeleteCronJob(ctx context.Context, in *DeleteCronJobRequest, opts ...grpc.CallOption) (*DeleteCronJobResponse, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error)
}

type k8SServiceClient struct {
	cc *grpc.ClientConn
}

func NewK8SServiceClient(cc *grpc.ClientConn) K8SServiceClient {
	return &k8SServiceClient{cc}
}

func (c *k8SServiceClient) GetConfigMap(ctx context.Context, in *GetConfigMapRequest, opts ...grpc.CallOption) (*GetConfigMapResponse, error) {
	out := new(GetConfigMapResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/GetConfigMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) GetCronJobs(ctx context.Context, in *GetCronJobsRequest, opts ...grpc.CallOption) (*GetCronJobsResponse, error) {
	out := new(GetCronJobsResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/GetCronJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) GetCronJob(ctx context.Context, in *GetCronJobRequest, opts ...grpc.CallOption) (*GetCronJobResponse, error) {
	out := new(GetCronJobResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/GetCronJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) CreateCronJob(ctx context.Context, in *CreateCronJobRequest, opts ...grpc.CallOption) (*CreateCronJobResponse, error) {
	out := new(CreateCronJobResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/CreateCronJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) DeleteCronJob(ctx context.Context, in *DeleteCronJobRequest, opts ...grpc.CallOption) (*DeleteCronJobResponse, error) {
	out := new(DeleteCronJobResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/DeleteCronJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*GetJobsResponse, error) {
	out := new(GetJobsResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/GetJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error) {
	out := new(DeleteJobResponse)
	err := c.cc.Invoke(ctx, "/pb.K8sService/DeleteJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// K8SServiceServer is the server API for K8SService service.
type K8SServiceServer interface {
	GetConfigMap(context.Context, *GetConfigMapRequest) (*GetConfigMapResponse, error)
	GetCronJobs(context.Context, *GetCronJobsRequest) (*GetCronJobsResponse, error)
	GetCronJob(context.Context, *GetCronJobRequest) (*GetCronJobResponse, error)
	CreateCronJob(context.Context, *CreateCronJobRequest) (*CreateCronJobResponse, error)
	DeleteCronJob(context.Context, *DeleteCronJobRequest) (*DeleteCronJobResponse, error)
	GetJobs(context.Context, *GetJobsRequest) (*GetJobsResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error)
}

func RegisterK8SServiceServer(s *grpc.Server, srv K8SServiceServer) {
	s.RegisterService(&_K8SService_serviceDesc, srv)
}

func _K8SService_GetConfigMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).GetConfigMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/GetConfigMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).GetConfigMap(ctx, req.(*GetConfigMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_GetCronJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCronJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).GetCronJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/GetCronJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).GetCronJobs(ctx, req.(*GetCronJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_GetCronJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCronJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).GetCronJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/GetCronJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).GetCronJob(ctx, req.(*GetCronJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_CreateCronJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCronJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).CreateCronJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/CreateCronJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).CreateCronJob(ctx, req.(*CreateCronJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_DeleteCronJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCronJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).DeleteCronJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/DeleteCronJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).DeleteCronJob(ctx, req.(*DeleteCronJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/GetJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).GetJobs(ctx, req.(*GetJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.K8sService/DeleteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).DeleteJob(ctx, req.(*DeleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _K8SService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.K8sService",
	HandlerType: (*K8SServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigMap",
			Handler:    _K8SService_GetConfigMap_Handler,
		},
		{
			MethodName: "GetCronJobs",
			Handler:    _K8SService_GetCronJobs_Handler,
		},
		{
			MethodName: "GetCronJob",
			Handler:    _K8SService_GetCronJob_Handler,
		},
		{
			MethodName: "CreateCronJob",
			Handler:    _K8SService_CreateCronJob_Handler,
		},
		{
			MethodName: "DeleteCronJob",
			Handler:    _K8SService_DeleteCronJob_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _K8SService_GetJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _K8SService_GetJob_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _K8SService_CreateJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _K8SService_DeleteJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k8s_service.proto",
}
